"""Ontology/SKOS domain index — ColBERT late-interaction over Qdrant for content-first input filtering.

The domain hierarchy is OUR SKOS ConceptScheme (``corpora/vocabulary/vocabulary.ttl``: ~549 concepts with
``skos:broader`` + dotted ``skos:notation``). Each concept is a domain/subdomain node; its ColBERT
multi-vector encodes prefLabel + altLabel + definition. A streamed document is encoded the same way and
scored against the index via Qdrant **native MaxSim**, yielding the nearest concept(s) → a hierarchical
roll-up (the notation path) + a belief. So the input filter is GROUNDED IN THE ONTOLOGY:

  * to expand coverage into a new domain you FIRST expand the SKOS hierarchy — which seeds derivation
    (the deriver grounds its content-extracted primitives in the seeded subtree); and
  * the classifier's **separation power is an early warning**: if concepts don't separate, the SKOS
    hierarchy needs specification/augmentation before its Qdrant entries have real classification power.

Mirrors the Atelier classify pattern (shared owner): ColBERTv2 (``colbert_encoder``) + Qdrant multivector
MaxSim. Qdrant runs on the aegir devenv ports (HTTP 6355).
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_QDRANT_URL = "http://localhost:6355"
DEFAULT_COLLECTION = "sdg_domains"
_REPO = Path(__file__).resolve().parents[3]
DEFAULT_VOCAB = _REPO / "corpora" / "vocabulary" / "vocabulary.ttl"


@dataclass
class SkosConcept:
    iri: str
    code: str = ""              # skos:notation, dotted (e.g. "2.1.3") — encodes the hierarchy
    pref_label: str = ""
    alt_label: str = ""
    definition: str = ""
    broader: str = ""           # parent IRI

    def text(self) -> str:
        """The text encoded into the concept's ColBERT multi-vector."""
        return ". ".join(p for p in (self.pref_label, self.alt_label, self.definition) if p).strip()

    def ancestor_codes(self) -> "list[str]":
        """Dotted-notation prefixes that are this concept's ancestors (e.g. '2.1.3' → ['2','2.1'])."""
        if not self.code:
            return []
        parts = self.code.split(".")
        return [".".join(parts[:i]) for i in range(1, len(parts))]


# ── SKOS loading ────────────────────────────────────────────────────────────────

_BLOCK = re.compile(r"<([^>]+)>\s+a\s+skos:Concept\s*;(.*?)(?:\.\s*\n)", re.S)
_PREF = re.compile(r'skos:prefLabel\s+"((?:[^"\\]|\\.)*)"')
_ALT = re.compile(r'skos:altLabel\s+"((?:[^"\\]|\\.)*)"')
_DEF = re.compile(r'skos:definition\s+"((?:[^"\\]|\\.)*)"')
_NOTE = re.compile(r'skos:notation\s+"((?:[^"\\]|\\.)*)"')
_BROADER = re.compile(r"skos:broader\s+<([^>]+)>")


def load_skos(path: "str | Path" = DEFAULT_VOCAB) -> "dict[str, SkosConcept]":
    """Parse the SKOS ConceptScheme TTL → {iri: SkosConcept}. Regex-based (avoids an rdflib dep); the file
    is machine-generated by build_skos_vocab so the shape is stable."""
    text = Path(path).read_text(encoding="utf-8")
    out: dict[str, SkosConcept] = {}
    for m in _BLOCK.finditer(text):
        iri, body = m.group(1), m.group(2)
        def _g(rx):  # noqa: E306
            mm = rx.search(body)
            return mm.group(1) if mm else ""
        out[iri] = SkosConcept(iri=iri, code=_g(_NOTE), pref_label=_g(_PREF), alt_label=_g(_ALT),
                               definition=_g(_DEF), broader=_g(_BROADER))
    return out


def subtree_codes(concepts: "dict[str, SkosConcept]", root: str) -> "set[str]":
    """All notation codes in the subtree rooted at ``root`` (a notation code OR a prefLabel, case-insensitive).
    Uses dotted-notation prefixing (robust) + broader as a fallback."""
    root_code = root
    if not re.fullmatch(r"[0-9.]+", root):  # given a label → resolve to its code
        rl = root.strip().lower()
        match = next((c for c in concepts.values() if c.pref_label.lower() == rl or c.alt_label.lower() == rl), None)
        if not match:
            return set()
        root_code = match.code
    return {c.code for c in concepts.values()
            if c.code == root_code or c.code.startswith(root_code + ".")}


# ── Qdrant multivector index ─────────────────────────────────────────────────────

def _client(url: str = DEFAULT_QDRANT_URL):
    from qdrant_client import QdrantClient
    return QdrantClient(url=url, timeout=60)


def build_index(*, vocab: "str | Path" = DEFAULT_VOCAB, url: str = DEFAULT_QDRANT_URL,
                collection: str = DEFAULT_COLLECTION, recreate: bool = True) -> dict:
    """Encode every SKOS concept's text → ColBERT multi-vectors → a Qdrant MAX_SIM collection. The ontology
    IS the index."""
    from qdrant_client import models

    from aegir.ontology.colbert_encoder import get_encoder

    concepts = load_skos(vocab)
    enc = get_encoder()
    client = _client(url)
    if recreate and client.collection_exists(collection):
        client.delete_collection(collection)
    if not client.collection_exists(collection):
        client.create_collection(
            collection_name=collection,
            vectors_config=models.VectorParams(
                size=enc.dim, distance=models.Distance.COSINE,
                multivector_config=models.MultiVectorConfig(comparator=models.MultiVectorComparator.MAX_SIM)),
        )
    items = [c for c in concepts.values() if c.text()]
    texts = [c.text() for c in items]
    vecs = enc.encode(texts)
    points = []
    for i, (c, v) in enumerate(zip(items, vecs)):
        points.append(models.PointStruct(id=i, vector=v.tolist(), payload={
            "iri": c.iri, "code": c.code, "pref_label": c.pref_label, "alt_label": c.alt_label,
            "broader": c.broader, "ancestor_codes": c.ancestor_codes()}))
    # batch the upsert — all 548 multivectors at once exceeds Qdrant's 32 MB JSON payload limit
    for start in range(0, len(points), 64):
        client.upsert(collection_name=collection, points=points[start:start + 64])
    return {"collection": collection, "concepts": len(items), "dim": enc.dim, "url": url}


def classify(text: str, *, url: str = DEFAULT_QDRANT_URL, collection: str = DEFAULT_COLLECTION,
             top_k: int = 5) -> "list[dict]":
    """Encode a document and return the top-k nearest SKOS concepts (Qdrant native MaxSim), each as
    {code, pref_label, score, ancestor_codes, iri}."""
    from aegir.ontology.colbert_encoder import get_encoder
    enc = get_encoder()
    client = _client(url)
    q = enc.encode_single(text).tolist()
    res = client.query_points(collection_name=collection, query=q, limit=top_k, with_payload=True).points
    return [{"score": float(p.score), **(p.payload or {})} for p in res]


def classify_hierarchical(text: str, *, top_k: int = 5, **kw) -> dict:
    """Top concept + belief + the hierarchical roll-up. ``belief`` = top-1 share of the top-k MaxSim mass;
    a flat distribution (low belief / low margin) means the SKOS hierarchy lacks separating power here."""
    hits = classify(text, top_k=top_k, **kw)
    if not hits:
        return {"hits": [], "top": None, "belief": 0.0, "margin": 0.0}
    scores = [h["score"] for h in hits]
    total = sum(scores) or 1.0
    margin = (scores[0] - scores[1]) if len(scores) > 1 else scores[0]
    top = hits[0]
    return {"hits": hits, "top": top, "belief": round(scores[0] / total, 3), "margin": round(margin, 3),
            "path": top.get("ancestor_codes", []) + [top.get("code", "")]}


def in_subtree(hit: dict, root_codes: "set[str]") -> bool:
    code = hit.get("code", "")
    return code in root_codes or any(a in root_codes for a in hit.get("ancestor_codes", []))


# ── early-warning diagnostic: does the SKOS hierarchy have classification power? ──

def separation_report(*, vocab: "str | Path" = DEFAULT_VOCAB, url: str = DEFAULT_QDRANT_URL,
                      collection: str = DEFAULT_COLLECTION, sample: int = 0) -> dict:
    """Self-retrieval + margin diagnostic. For each concept, classify its OWN text and check whether it
    retrieves itself at rank-1, and the rank1−rank2 margin. Low self-retrieval / low margin = concepts that
    are not separable → the SKOS hierarchy needs specification/augmentation before its entries can classify
    real input. Returns aggregate metrics + the most-confusable concept pairs (the augmentation worklist)."""
    concepts = [c for c in load_skos(vocab).values() if c.text()]
    if sample:
        concepts = concepts[:sample]
    self_hits = margins = 0
    margin_sum = 0.0
    confusions: list[dict] = []
    for c in concepts:
        h = classify_hierarchical(c.text(), top_k=3, url=url, collection=collection)
        top = h.get("top") or {}
        is_self = top.get("code") == c.code or top.get("pref_label") == c.pref_label
        self_hits += int(is_self)
        margin_sum += h["margin"]
        margins += 1
        if not is_self:
            confusions.append({"concept": c.pref_label, "code": c.code,
                               "confused_with": top.get("pref_label"), "with_code": top.get("code"),
                               "margin": h["margin"]})
    n = len(concepts) or 1
    confusions.sort(key=lambda x: x["margin"])
    return {"concepts": len(concepts), "self_retrieval": round(self_hits / n, 3),
            "mean_margin": round(margin_sum / max(1, margins), 4),
            "confusable": confusions[:25],
            "verdict": ("hierarchy has classification power" if self_hits / n >= 0.85
                        else "WEAK — SKOS hierarchy needs specification/augmentation (see confusable)")}
