"""``aegir.lineup sync`` — SHARE: publish the materialized ontology Data Product to the
``corpora`` (sdg-corpora) submodule, the reasoner-gated know→share boundary.

``build`` materializes the products locally (what we KNOW, the gitignored ``build/dev``
projection); ``sync`` publishes the ontology Data Product to the SHARE tier — the
``corpora`` submodule, which is attribution-clean and public. It regenerates, from the live
ontology SoT (``src/aegir/ontology``), the shared artifacts under ``corpora/``:

  • ontology/   — catalog mirror (the 7 family JSONs, incl. the ``broader`` subsumption
                  hierarchy) + family_complex.json + sdg-vocab.ttl + SLOT_DSL.md
  • vocabulary/ — SKOS ConceptScheme + Atelier ReferenceCategory annotations (build_skos_vocab)
  • ddl/        — the ontology→SQL DDL spine (build_ddl_spine)

Gate: the ontology schema-CI (``check_ontology_schema`` — TTL well-formedness, labels/
definitions, BFO ancestry, SPARQL totality). A broken ontology is never published. (The
HermiT consistency gate is applied upstream, at hierarchy-authoring time, by
``mediate_hierarchy``; a full reasoner pass at publish is a future deepening.)

The content Data Product (``corpora/corpus`` — the generated chapters) is NOT touched here:
it is regenerated by the generation pipeline, not derived from the catalog.

``--commit`` commits the corpora submodule locally; ``--push`` publishes it to the shared
``zndx/sdg-corpora`` remote (the external share — explicit, never implicit). Default is a
dry materialization + diff so the change can be reviewed first.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC_ONTO = REPO / "src" / "aegir" / "ontology"
CORPORA = REPO / "corpora"


def _sh(cmd: list[str], cwd: Path = REPO) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)


def _last(out: str, default: str = "") -> str:
    lines = [ln for ln in (out or "").splitlines() if ln.strip()]
    return lines[-1] if lines else default


def _gate() -> bool:
    """Reasoner/schema gate — refuse to publish a structurally broken ontology."""
    r = _sh([sys.executable, "scripts/check_ontology_schema.py"])
    print("   " + _last(r.stdout, "(schema-CI produced no output)"))
    if r.returncode != 0:
        print("   GATE FAILED — refusing to publish.\n" + (r.stdout or r.stderr or "")[-600:])
    return r.returncode == 0


def _mirror_ontology() -> None:
    dst = CORPORA / "ontology"
    (dst / "catalog").mkdir(parents=True, exist_ok=True)
    n = 0
    for f in sorted((SRC_ONTO / "catalog").glob("0[1-8]_*.json")):
        if ".candidate." in f.name:        # staging copies — never shared
            continue
        shutil.copy2(f, dst / "catalog" / f.name)
        n += 1
    for name in ("family_complex.json", "sdg-vocab.ttl", "SLOT_DSL.md"):
        src = SRC_ONTO / name
        if src.exists():
            shutil.copy2(src, dst / name)
    print(f"   mirrored {n} family catalogs + family_complex + sdg-vocab.ttl + SLOT_DSL.md")


def _regen_vocabulary() -> bool:
    r = _sh([sys.executable, "scripts/build_skos_vocab.py", "--out", str(CORPORA / "vocabulary")])
    print("   " + _last(r.stdout, "(SKOS build produced no output)"))
    if r.returncode != 0:
        print("   SKOS build FAILED:\n" + (r.stderr or "")[-400:])
    return r.returncode == 0


def _regen_ddl() -> bool:
    """Regenerate the DDL spine, IDEMPOTENTLY. build_ddl_spine's <run_id> is a content hash of
    the catalog, so an unchanged ontology yields the same run_id. The parquet/manifest bytes are
    NOT byte-stable run-to-run (parquet metadata + manifest timestamp), so we build into a temp,
    and only swap into corpora/ddl when the run_id actually changed — otherwise keep the committed
    bytes so a no-op sync produces no spurious corpora commit."""
    import tempfile
    out = CORPORA / "ddl"
    out.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="ddl_spine_"))
    try:
        r = _sh([sys.executable, "scripts/build_ddl_spine.py", "--output-dir", str(tmp)])
        if r.returncode != 0:
            print("   DDL spine FAILED:\n" + (r.stderr or "")[-400:])
            return False
        runs = [d for d in tmp.iterdir() if d.is_dir()]
        if not runs:
            print("   DDL spine produced no run dir")
            return False
        new_run = runs[0]
        existing = out / new_run.name
        if existing.exists():
            print(f"   DDL spine unchanged (run {new_run.name}) — kept committed bytes (idempotent)")
            return True
        for d in out.iterdir():                # catalog changed → new run_id: drop stale runs, swap in
            if d.is_dir():
                shutil.rmtree(d)
        shutil.move(str(new_run), str(existing))
        print(f"   DDL spine rebuilt → run {new_run.name}")
        return True
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def run(args=None) -> int:
    commit = bool(getattr(args, "commit", False))
    push = bool(getattr(args, "push", False))
    print("aegir.lineup sync — SHARE: ontology Data Product → corpora (sdg-corpora)")
    if not CORPORA.exists() or not (CORPORA / ".git").exists():
        print(f"  corpora submodule not checked out at {CORPORA} — `git submodule update --init`.")
        return 1

    print("1) reasoner/schema gate (check_ontology_schema)")
    if not _gate():
        return 1
    print("2) mirror ontology SoT → corpora/ontology/")
    _mirror_ontology()
    print("3) regenerate SKOS vocabulary → corpora/vocabulary/")
    _regen_vocabulary()
    print("4) regenerate DDL spine → corpora/ddl/")
    _regen_ddl()

    st = _sh(["git", "status", "--short"], cwd=CORPORA)
    changed = bool((st.stdout or "").strip())
    print("5) corpora working-tree diff:")
    print((st.stdout or "").rstrip() if changed else "   (no working-tree changes — ontology already in sync)")

    # (a) commit any regen changes from THIS run
    if changed:
        if not (commit or push):
            print("done — regenerated in the working tree (not committed).\n"
                  "  review the diff, then re-run with --commit (and --push to publish to zndx/sdg-corpora).")
            return 0
        _sh(["git", "add", "-A"], cwd=CORPORA)
        msg = "Re-sync ontology Data Product from aegir SoT (catalog incl. broader hierarchy + SKOS + DDL)"
        c = _sh(["git", "commit", "-m", msg], cwd=CORPORA)
        print("   corpora commit: " + _last(c.stdout + c.stderr, "(commit produced no output)"))

    # (b) push is BRANCH-WIDE — publishes every pending commit (this run's regen AND any other
    #     unpushed corpora work, e.g. the corpus collections committed out-of-band), not just what
    #     this run regenerated. `git push` is a no-op ("Everything up-to-date") when nothing pends.
    if push:
        ahead = _last((_sh(["git", "rev-list", "--count", "@{u}..HEAD"], cwd=CORPORA).stdout or "").strip())
        p = _sh(["git", "push"], cwd=CORPORA)
        print(f"   push ({ahead or '?'} pending): " + _last(p.stderr + p.stdout, "ok"))
        print("   NOTE: if corpora HEAD moved, bump the aegir submodule pointer (git add corpora && commit).")
    elif changed and commit:
        print("   committed locally; NOT pushed — re-run with --push to publish to zndx/sdg-corpora.")
    elif not changed:
        print("done — corpora already in sync; nothing to push (re-run with --push if there are "
              "unpushed commits to publish).")
    return 0
