"""``aegir.lineup sync`` — SHARE: publish the materialized ontology Data Product to the
``corpora`` (sdg-corpora) submodule, the reasoner-gated know→share boundary.

``build`` materializes the products locally (what we KNOW, the gitignored ``build/dev``
projection); ``sync`` publishes the ontology Data Product to the SHARE tier — the
``corpora`` submodule, which is attribution-clean and public. It regenerates, from the live
ontology SoT (``src/aegir/ontology``), the shared artifacts under ``corpora/``:

  • ontology/   — catalog mirror (the derived catalog file(s), incl. the ``broader``
                  subsumption hierarchy) + sdg-vocab.ttl + SLOT_DSL.md
  • vocabulary/ — SKOS ConceptScheme + Atelier ReferenceCategory annotations (build_skos_vocab)
  • ddl/        — the ontology→SQL DDL spine (build_ddl_spine)

Gate: THREE ANDed checks — (1) the ontology schema-CI (``check_ontology_schema`` — TTL
well-formedness, labels/definitions, BFO ancestry, SPARQL totality); (2) the OQuaRE
ontology-quality gate (``ontology_oquare`` — a hard floor on the realized OWL: aggregate
≥3.5 AND Functional-Adequacy ≥3.0, forcing definitional rigor + BFO discipline); (3) the
SUFFICIENCY gate (task #7) — discriminability + domain-mid-tier + 0-unsat RE-MEASURED at
gate time from the release-candidate run (``sdg_run_root``), so an insufficient-differentia
(pre-taxonomy flat) ontology is never published. A broken or sub-rigor ontology is never
published. OQuaRE consumes the upstream HermiT verdict from
the realizer's certificate (JVM-free; the consistency gate is applied upstream, at
hierarchy-authoring time, by ``mediate_hierarchy``).

The content Data Product (``corpora/corpus`` — the generated chapters) is NOT touched here:
it is regenerated by the generation pipeline, not derived from the catalog.

``--commit`` commits the corpora submodule locally; ``--push`` publishes it to the shared
``zndx/sdg-corpora`` remote (the external share — explicit, never implicit). Default is a
dry materialization + diff so the change can be reviewed first.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC_ONTO = REPO / "src" / "aegir" / "ontology"
CORPORA = REPO / "corpora"


def _sh(cmd: list[str], cwd: Path = REPO) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)


def _last(out: str, default: str = "") -> str:
    lines = [ln for ln in (out or "").splitlines() if ln.strip()]
    return lines[-1] if lines else default


def _gate() -> bool:
    """Publish gate — refuse to publish a structurally broken OR sub-rigor ontology. Two ANDed checks:

      1. schema-CI (`check_ontology_schema`) — TTL well-formedness, labels/definitions, BFO ancestry,
         SPARQL totality. Gates the CATALOG (the templates).
      2. OQuaRE (`ontology_oquare`) — the hard ontology-quality floor on the realized OWL: aggregate ≥3.5
         AND Functional-Adequacy ≥3.0, forcing definitional rigor + BFO discipline before the ontology
         Data Product is shared. Consumes the upstream HermiT verdict from HERMIT_CERTIFICATE.md (JVM-free;
         the reasoner gate stays upstream). Fail-closed if the realized OWL is absent (rebuild it first).
    """
    r = _sh([sys.executable, "scripts/check_ontology_schema.py"])
    print("   schema-CI: " + _last(r.stdout, "(no output)"))
    schema_ok = r.returncode == 0
    if not schema_ok:
        print("   schema-CI FAILED.\n" + (r.stdout or r.stderr or "")[-400:])

    owl = CORPORA / "ontology" / "sdg-ontology.owl"
    cert = CORPORA / "ontology" / "HERMIT_CERTIFICATE.md"
    if owl.exists():
        oq = _sh([sys.executable, "scripts/ontology_oquare.py", str(owl), "--certificate", str(cert)])
        print("   OQuaRE:    " + _last(oq.stdout, "(no output)"))
        oq_ok = oq.returncode == 0
        if not oq_ok:
            print((oq.stdout or oq.stderr or "")[-500:])
    else:
        print(f"   OQuaRE:    ⊘ no realized OWL at {owl.relative_to(REPO)} — run build_realized_ontology.py first")
        oq_ok = False  # the ontology Data Product includes the realized OWL — never publish it ungated

    # 3. SUFFICIENCY (task #7 — the taxonomy release's own floor): RE-MEASURED at gate time from the
    #    release-candidate run's shipped artifacts (sdg_run_root — never a stale number). Floors:
    #    type-signature discriminability ≥ 0.95 (v0.6 baseline 0.9944; the pre-taxonomy flat ontology
    #    fails), a real domain mid-tier (taxonomy_parents_domain ≥ 5 — genus layer present), and the
    #    run's HermiT certificate clean (0 unsat). Fail-closed when the run artifacts are absent.
    suff_ok = False
    try:
        import json as _json
        from aegir.lineup.sources import sdg_run_root
        from aegir.ontology.discriminability import compute
        root = sdg_run_root()
        if root and (root / "ontology" / "shapes.ttl").exists() \
                and (root / "ontology" / "sdg-ontology.omn").exists():
            m = compute(root / "ontology" / "shapes.ttl", root / "ontology" / "sdg-ontology.omn")
            cert = _json.loads((root / "ontology" / "certificate.json").read_text()) \
                if (root / "ontology" / "certificate.json").exists() else {}
            d, mid = m["discriminability_typesig"], m["structural_adequacy"]["taxonomy_parents_domain"]
            unsat = len(cert.get("unsat", [None]))          # missing cert reads as dirty — fail-closed
            suff_ok = d >= 0.95 and mid >= 5 and unsat == 0
            print(f"   sufficiency: discriminability={d} (≥0.95) · domain mid-tier={mid} (≥5) · "
                  f"unsat={unsat} (=0) → {'ok' if suff_ok else 'FAILED'}  [{root.name}]")
        else:
            print("   sufficiency: ⊘ no release-candidate run artifacts (sdg_run_root) — fail-closed")
    except Exception as e:  # noqa: BLE001
        print(f"   sufficiency: FAILED to measure ({str(e)[:120]}) — fail-closed")

    if not (schema_ok and oq_ok and suff_ok):
        print("   GATE FAILED — refusing to publish.")
    return schema_ok and oq_ok and suff_ok


def _mirror_ontology() -> None:
    dst = CORPORA / "ontology"
    (dst / "catalog").mkdir(parents=True, exist_ok=True)
    n = 0
    live = set()
    from aegir.ontology.schema import catalog_files
    for f in catalog_files(SRC_ONTO / "catalog"):
        shutil.copy2(f, dst / "catalog" / f.name)
        live.add(f.name)
        n += 1
    # retired/renamed catalog files leave the mirror too (incl. the 0*-era family names)
    for stale in sorted(list((dst / "catalog").glob("0[1-8]_*.json"))
                        + list((dst / "catalog").glob("catalog.json"))):
        if stale.name not in live:
            stale.unlink()
            print(f"   mirror: dropped retired catalog {stale.name}")
    for name in ("sdg-vocab.ttl", "SLOT_DSL.md"):  # family_complex.json retired (pre-wired gate → measured stat)
        src = SRC_ONTO / name
        if src.exists():
            shutil.copy2(src, dst / name)
    (dst / "family_complex.json").unlink(missing_ok=True)  # drop the retired artifact from the mirror
    print(f"   mirrored {n} catalog file(s) + sdg-vocab.ttl + SLOT_DSL.md")
    _standalone_bundle(dst)


IMPORT_IRI = "https://signals.zndx.org/sdg/imports/cco-module"
COMPREHENSIVE_IRI = "https://signals.zndx.org/sdg/comprehensive"


def _standalone_bundle(dst: Path) -> None:
    """Make corpora/ontology/ COMPLETELY STANDALONE (RH 2026-07-22): the repo is the
    publication of the results — a fresh clone must load in Protégé with no aegir.

    * imports/cco-module.ttl ships (the BFO + π(CCO) theory the ontology imports).
    * Machine-local `file:` imports rewrite to the LOGICAL import IRI; catalog-v001.xml
      (the standard Protégé/OWLAPI XML-catalog mechanism) maps it to the shipped file.
    * sdg-ontology-comprehensive.{omn,owl} ships the CERTIFIED UNION — the full realized
      extent (catalog + entity generations + armed domains + grounding), under its own
      ontology IRI so it coexists with the catalog ontology in one workspace.
    Publication-time transform only: aegir-internal artifacts keep their local imports.
    """
    import re as _re
    mod_src = REPO / "build/grounding/cco-module.ttl"
    if mod_src.exists():
        (dst / "imports").mkdir(exist_ok=True)
        shutil.copy2(mod_src, dst / "imports" / "cco-module.ttl")

    def _rewrite(p_: Path, also_iri: "tuple[str, str] | None" = None) -> None:
        if not p_.exists():
            return
        t = p_.read_text()
        t = _re.sub(r'file:/[^\s>"]*cco-module\.ttl', IMPORT_IRI, t)
        if also_iri:
            t = t.replace(also_iri[0], also_iri[1])
        p_.write_text(t)

    _rewrite(dst / "sdg-ontology.omn")
    _rewrite(dst / "sdg-ontology.owl")
    comp_omn = REPO / "build/unified_grounded/sdg-ontology.omn"
    comp_owl = REPO / "build/unified_grounded/sdg-union.owl"
    n_comp = 0
    if comp_omn.exists():
        shutil.copy2(comp_omn, dst / "sdg-ontology-comprehensive.omn")
        _rewrite(dst / "sdg-ontology-comprehensive.omn",
                 also_iri=("Ontology: <https://signals.zndx.org/sdg>",
                           f"Ontology: <{COMPREHENSIVE_IRI}>"))
        n_comp += 1
    if comp_owl.exists():
        shutil.copy2(comp_owl, dst / "sdg-ontology-comprehensive.owl")
        _rewrite(dst / "sdg-ontology-comprehensive.owl",
                 also_iri=('ontologyIRI="https://signals.zndx.org/sdg"',
                           f'ontologyIRI="{COMPREHENSIVE_IRI}"'))
        n_comp += 1
    (dst / "catalog-v001.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">\n'
        f'  <uri name="{IMPORT_IRI}" uri="imports/cco-module.ttl"/>\n'
        '</catalog>\n')
    print(f"   standalone bundle: theory module shipped · imports → {IMPORT_IRI} "
          f"(catalog-v001.xml) · comprehensive union artifacts: {n_comp}")
    _emit_entity_associations()


def _emit_entity_associations() -> None:
    """ontology → relational-entity associations, BY CONSTRUCTION, published (RH
    2026-07-23). The builder lives in aegir.ontology.associations (ONE closure
    discipline, two conductors): the FLOW's ddl stage emits natively at generation;
    this release-act call re-emits idempotently over the released spine run so the
    published artifact always reflects the released bytes."""
    try:
        from aegir.ontology.associations import emit_spine_associations
        s = emit_spine_associations()
        if s:
            print(f"   entity associations: {s['n_classes']} classes · {s['n_unpopulated']} unpopulated "
                  f"(the generative-pass worklist) → ddl/{s['run']}/ontology_entity_associations.json")
    except Exception as e:  # noqa: BLE001
        print(f"   entity associations skipped: {e}")


def _regen_vocabulary() -> bool:
    r = _sh([sys.executable, "scripts/build_skos_vocab.py", "--out", str(CORPORA / "vocabulary")])
    print("   " + _last(r.stdout, "(SKOS build produced no output)"))
    if r.returncode != 0:
        print("   SKOS build FAILED:\n" + (r.stderr or "")[-400:])
        return False
    # the SCHEME layer ships verbatim (RH 2026-07-23: six tops + PRODML/SYSML mapped-spec
    # schemes CONFIRMED — the overlay is the ConceptScheme SoT; vocabulary.ttl carries
    # the derived concept census, this file carries the graduated organization)
    shutil.copy2(SRC_ONTO / "domain_concepts.ttl", CORPORA / "vocabulary" / "domain-concepts.ttl")
    print("   scheme layer shipped → vocabulary/domain-concepts.ttl (confirmed tops + "
          "mapped-spec schemes)")
    return True


def _regen_ddl() -> bool:
    """Regenerate the DDL spine, IDEMPOTENTLY. build_ddl_spine's <run_id> is a content hash of
    the catalog, so an unchanged ontology yields the same run_id. The parquet/manifest bytes are
    NOT byte-stable run-to-run (parquet metadata + manifest timestamp), so we build into a temp,
    and only swap into corpora/ddl when the run_id actually changed — otherwise keep the committed
    bytes so a no-op sync produces no spurious corpora commit."""
    import tempfile
    out = CORPORA / "ddl"
    out.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="ddl_spine_"))
    try:
        r = _sh([sys.executable, "scripts/build_ddl_spine.py", "--output-dir", str(tmp)])
        if r.returncode != 0:
            print("   DDL spine FAILED:\n" + (r.stderr or "")[-400:])
            return False
        runs = [d for d in tmp.iterdir() if d.is_dir()]
        if not runs:
            print("   DDL spine produced no run dir")
            return False
        new_run = runs[0]
        existing = out / new_run.name
        if existing.exists():
            print(f"   DDL spine unchanged (run {new_run.name}) — kept committed bytes (idempotent)")
            return True
        for d in out.iterdir():                # catalog changed → new run_id: drop stale runs, swap in
            if d.is_dir():
                shutil.rmtree(d)
        shutil.move(str(new_run), str(existing))
        print(f"   DDL spine rebuilt → run {new_run.name}")
        return True
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _emit_sql_bundle() -> bool:
    """Directly-loadable SQL (RH 2026-07-23): derive the per-database ``sql/`` bundle
    from the released spine parquets (postgres record-assembled + polyglot-transpiled;
    trino/spark native), then PROVE postgres loadability against the devenv instance.
    Degradations print, never silent; exclusions are named."""
    runs = sorted((CORPORA / "ddl").glob("*/manifest.json"))
    if not runs:
        print("   no spine run — bundle skipped")
        return True
    run_dir = runs[-1].parent
    try:
        from aegir.ontology.sql_bundle import emit_sql_bundle
        s = emit_sql_bundle(run_dir)
        for d, x in s["dialects"].items():
            extra = f" · EXCLUDED {x['excluded']}" if x.get("excluded") else ""
            print(f"   {d}: {x['tables']} tables · {x['insert_rows']} rows · "
                  f"{x['views']} views{extra}")
    except Exception as e:  # noqa: BLE001
        print(f"   sql bundle FAILED: {e}")
        return False
    return _verify_pg_load(run_dir)


def _verify_pg_load(run_dir: Path) -> bool:
    """The loadability gate: load the postgres flavor into the devenv instance
    (database ``sdg_corpora``, recreated each pass and LEFT LOADED — at the ready for
    direct testing). An unreachable instance degrades VISIBLY; a load failure fails."""
    import os
    env = {**os.environ,
           "PGHOST": os.environ.get("PGHOST", "127.0.0.1"),
           "PGPORT": os.environ.get("PGPORT", "5555"),
           "PGUSER": os.environ.get("PGUSER", os.environ.get("USER", "postgres"))}

    def _psql(*args: str) -> subprocess.CompletedProcess:
        return subprocess.run(["psql", *args], capture_output=True, text=True, env=env)

    sqldir = run_dir / "sql" / "postgres"
    pre = _psql("-d", "postgres", "-qc", "DROP DATABASE IF EXISTS sdg_corpora",
                "-c", "CREATE DATABASE sdg_corpora")
    if pre.returncode != 0:
        print(f"   pg load SKIPPED (instance unavailable): "
              f"{(pre.stderr or '').strip()[:120]}")
        return True
    r = _psql("-d", "sdg_corpora", "-v", "ON_ERROR_STOP=1", "-q",
              "-f", str(sqldir / "00_schema.sql"), "-f", str(sqldir / "01_data.sql"),
              "-f", str(sqldir / "02_views.sql"))
    if r.returncode != 0:
        print(f"   pg load FAILED: {(r.stderr or '').strip()[-300:]}")
        return False
    m = _psql("-d", "sdg_corpora", "-tAc",
              "SELECT count(*) FROM information_schema.tables WHERE "
              "table_schema='public' AND table_type='BASE TABLE'")
    v = _psql("-d", "sdg_corpora", "-tAc",
              "SELECT count(*) FROM information_schema.views WHERE table_schema='public'")
    print(f"   pg load VERIFIED → database sdg_corpora "
          f"({(m.stdout or '').strip()} tables · {(v.stdout or '').strip()} views) — "
          "at the ready for direct testing")
    return True


def _mirror_comprehensive() -> bool:
    """Ship the comprehensive (certified-union) lowering (RH 2026-07-23: comprehensive
    is the DEFAULT scope): mirror build/comprehensive_release → corpora/ddl-comprehensive/
    <omn-sha16>/, content-addressed and swap-only-on-change like the spine. HARD GATE:
    a missing or non-consistent certificate ships NOTHING (never publish uncertified);
    the postgres loadability gate then proves the shipped DDL (database
    ``sdg_comprehensive``, left loaded for direct testing)."""
    import hashlib
    src = REPO / "build/comprehensive_release"
    need = ["ddl.sql", "plan.json", "shapes.ttl", "certificate.json", "structure.json",
            "ontology_entity_associations.json", "sdg-ontology.omn"]
    if not all((src / f).exists() for f in need):
        print("   comprehensive release dir incomplete — not shipped (run the "
              "comprehensive realize first)")
        return True
    try:
        cert = json.loads((src / "certificate.json").read_text())
    except Exception as e:  # noqa: BLE001
        print(f"   comprehensive certificate unreadable — NOT shipped: {e}")
        return False
    if cert.get("skipped") or not cert.get("isConsistent"):
        print(f"   comprehensive certificate not green (skipped={cert.get('skipped')} "
              f"consistent={cert.get('isConsistent')}) — NOT shipped")
        return False
    run_id = hashlib.sha256((src / "sdg-ontology.omn").read_bytes()).hexdigest()[:16]
    out = CORPORA / "ddl-comprehensive"
    dst = out / run_id
    if dst.exists():
        print(f"   comprehensive unchanged (run {run_id}) — kept committed bytes (idempotent)")
    else:
        out.mkdir(parents=True, exist_ok=True)
        for d in out.iterdir():                # content changed → new id: swap
            if d.is_dir():
                shutil.rmtree(d)
        dst.mkdir()
        for f in need:
            shutil.copy2(src / f, dst / f)
        (dst / "README.md").write_text(
            f"# Comprehensive relational lowering — `{run_id}`\n\n"
            "kvasir's deterministic DDL over the CERTIFIED union (released catalog ∪ "
            "entity generations ∪ armed domains ∪ mapped-spec entities): schema-only "
            "(no row data), postgres-proven, FK constraints as a post-CREATE ALTER "
            "pass so it loads in one `psql -f ddl.sql`.\n\n"
            "| file | role |\n|---|---|\n"
            "| `ddl.sql` | the loadable schema (see `just load-comprehensive`) |\n"
            "| `plan.json` | kvasir's cited election record (class/property IRIs per "
            "table/junction/lookup) |\n"
            "| `ontology_entity_associations.json` | the closure artifact — every "
            "relational entity → its ontological source (exact-IRI, generator-recorded) |\n"
            "| `shapes.ttl` | SHACL Core constraint view |\n"
            "| `certificate.json` | the HermiT verdict this release shipped under |\n"
            "| `structure.json` | SchemaPile structure score |\n"
            "| `sdg-ontology.omn` | the certified union the DDL was lowered from |\n")
        print(f"   comprehensive shipped → ddl-comprehensive/{run_id} "
              f"(cert: consistent, {cert.get('n_classes')} classes)")
    # loadability gate (schema-only): database sdg_comprehensive, recreated + left loaded
    import os
    env = {**os.environ,
           "PGHOST": os.environ.get("PGHOST", "127.0.0.1"),
           "PGPORT": os.environ.get("PGPORT", "5555"),
           "PGUSER": os.environ.get("PGUSER", os.environ.get("USER", "postgres"))}

    def _psql(*a: str) -> subprocess.CompletedProcess:
        return subprocess.run(["psql", *a], capture_output=True, text=True, env=env)

    pre = _psql("-d", "postgres", "-qc", "DROP DATABASE IF EXISTS sdg_comprehensive",
                "-c", "CREATE DATABASE sdg_comprehensive")
    if pre.returncode != 0:
        print(f"   comprehensive pg load SKIPPED (instance unavailable): "
              f"{(pre.stderr or '').strip()[:120]}")
        return True
    r = _psql("-d", "sdg_comprehensive", "-v", "ON_ERROR_STOP=1", "-q",
              "-f", str(dst / "ddl.sql"))
    if r.returncode != 0:
        print(f"   comprehensive pg load FAILED: {(r.stderr or '').strip()[-300:]}")
        return False
    m = _psql("-d", "sdg_comprehensive", "-tAc",
              "SELECT count(*) FROM information_schema.tables WHERE table_schema='public'")
    print(f"   comprehensive pg load VERIFIED → database sdg_comprehensive "
          f"({(m.stdout or '').strip()} tables) — at the ready for direct testing")
    return True


def run(args=None) -> int:
    commit = bool(getattr(args, "commit", False))
    push = bool(getattr(args, "push", False))
    print("aegir.lineup sync — SHARE: ontology Data Product → corpora (sdg-corpora)")
    if not CORPORA.exists() or not (CORPORA / ".git").exists():
        print(f"  corpora submodule not checked out at {CORPORA} — `git submodule update --init`.")
        return 1

    print("1) reasoner/schema gate (check_ontology_schema)")
    if not _gate():
        return 1
    print("2) mirror ontology SoT → corpora/ontology/")
    _mirror_ontology()
    print("3) regenerate SKOS vocabulary → corpora/vocabulary/")
    _regen_vocabulary()
    print("4) regenerate DDL spine → corpora/ddl/")
    _regen_ddl()
    print("4b) loadable SQL bundle (postgres/trino/spark) → corpora/ddl/<run>/sql/")
    _emit_sql_bundle()
    print("4c) comprehensive lowering (certificate-gated) → corpora/ddl-comprehensive/")
    _mirror_comprehensive()

    st = _sh(["git", "status", "--short"], cwd=CORPORA)
    changed = bool((st.stdout or "").strip())
    print("5) corpora working-tree diff:")
    print((st.stdout or "").rstrip() if changed else "   (no working-tree changes — ontology already in sync)")

    # (a) commit any regen changes from THIS run
    if changed:
        if not (commit or push):
            print("done — regenerated in the working tree (not committed).\n"
                  "  review the diff, then re-run with --commit (and --push to publish to zndx/sdg-corpora).")
            return 0
        _sh(["git", "add", "-A"], cwd=CORPORA)
        msg = "Re-sync ontology Data Product from aegir SoT (catalog incl. broader hierarchy + SKOS + DDL)"
        c = _sh(["git", "commit", "-m", msg], cwd=CORPORA)
        print("   corpora commit: " + _last(c.stdout + c.stderr, "(commit produced no output)"))

    # (b) push is BRANCH-WIDE — publishes every pending commit (this run's regen AND any other
    #     unpushed corpora work, e.g. the corpus collections committed out-of-band), not just what
    #     this run regenerated. `git push` is a no-op ("Everything up-to-date") when nothing pends.
    if push:
        ahead = _last((_sh(["git", "rev-list", "--count", "@{u}..HEAD"], cwd=CORPORA).stdout or "").strip())
        p = _sh(["git", "push"], cwd=CORPORA)
        print(f"   push ({ahead or '?'} pending): " + _last(p.stderr + p.stdout, "ok"))
        print("   NOTE: if corpora HEAD moved, bump the aegir submodule pointer (git add corpora && commit).")
    elif changed and commit:
        print("   committed locally; NOT pushed — re-run with --push to publish to zndx/sdg-corpora.")
    elif not changed:
        print("done — corpora already in sync; nothing to push (re-run with --push if there are "
              "unpushed commits to publish).")
    return 0
