"""Parallel register-specialized ACP prose harnesses + work-queue driver (#141).

RH architecture (2026-07-04): prose is generated by a WORK QUEUE of ``(construct × register ×
backend)`` items pushed through FIXED-SIZE per-backend worker pools. Each item runs one ACP agent
harness — register-specialized (natural / semantic) and tool/resource-equipped over MCP (the
semantic harness gets kvasir DDL-check tools + a SHACL grounding resource; more tools per the
loadout roadmap). The agent iterates against its tools while writing; the CLIENT owns the tools so
the agent can check but never fake (the membrane doctrine, ``refine/acp/client.py``).

Backends are pluggable — ``local`` (mistral vibe-acp → Qwen3.6 on the engine's :8100 vLLM),
``grok`` (Grok Build subscription), ``xai`` (metered API). Both registers run on ``local`` first;
grok swaps in as the local+API worker mix shifts (a fixed pool per backend caps concurrency).

The unit is :func:`run_item`; the driver is :func:`run_queue` (per-backend ``asyncio.Semaphore``),
which generalizes to a Metaflow ``foreach`` with resource limits.
"""
from __future__ import annotations

import asyncio
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from aegir.refine._propose import _prompt, _strip_reasoning
from aegir.refine.acp import BaseACPClient, MCPServer, grok_acp_spec, vibe_acp_spec

REPO = Path(__file__).resolve().parents[3]
FORK = os.environ.get("AEGIR_FORK_DIR", str(REPO / "components/oss-mistral-cli"))

# vibe-acp config pointing at the local vLLM OpenAI endpoint (the engine's :8100).
_LOCAL_TOML = (
    'active_model = "local"\nsystem_prompt_id = "aegir_writer"\n'
    '[[providers]]\nname = "local-vllm"\napi_base = "http://127.0.0.1:8100/v1"\n'
    'api_style = "openai"\n[[models]]\nname = "instruct"\nprovider = "local-vllm"\nalias = "local"\n'
)


def backend_spec(backend: str, home: str):
    """``(AgentSpec, cfg_toml|None, model_id, provider)`` for a NAMED backend (the work-queue
    parameter form of ``_propose._agent_spec``'s env form). ``local`` → vibe-acp→Qwen3.6;
    ``grok`` → the unmetered Grok Build CLI; ``xai`` → the metered xAI API."""
    b = backend.lower()
    if b in ("grok", "grok-build"):
        return grok_acp_spec(home), None, os.environ.get("AEGIR_GROK_MODEL", "grok"), "grok-build"
    if b in ("xai", "xai-api"):
        if not os.environ.get("XAI_API_KEY"):
            raise RuntimeError("backend=xai but XAI_API_KEY is unset (metered)")
        model = os.environ.get("AEGIR_XAI_MODEL", "grok-4.3")
        toml = ('active_model = "remote"\nsystem_prompt_id = "aegir_writer"\n'
                '[[providers]]\nname = "xai"\napi_base = "https://api.x.ai/v1"\n'
                'api_style = "openai"\napi_key_env_var = "XAI_API_KEY"\n'
                f'[[models]]\nname = "{model}"\nprovider = "xai"\nalias = "remote"\n')
        return vibe_acp_spec(FORK, home), toml, model, "xai-api"
    return vibe_acp_spec(FORK, home), _LOCAL_TOML, "instruct", "engine"


# The devenv venv python directly — NOT `uv run` (whose 2-3s env-resolve latency races the fork's
# MCP handshake and yields an empty response; the direct interpreter starts instantly).
_VENV_PY = str(REPO / ".devenv/state/venv/bin/python")


def kvasir_mcp_server() -> MCPServer:
    """The kvasir DDL/consistency/SHACL toolbox as a stdio MCP server (``scripts/mcp_kvasir.py``).
    Forwards the parent environment so the agent-spawned subprocess resolves its interpreter +
    imports (an empty env hangs the handshake — the agent-spawn env-stripping bug)."""
    py = _VENV_PY if Path(_VENV_PY).exists() else "python"
    return MCPServer(name="kvasir", command=py, args=[str(REPO / "scripts/mcp_kvasir.py")],
                     cwd=str(REPO), env=dict(os.environ))


class kvasir_http_server:
    """The same kvasir toolbox served over streamable-http, for agents whose ACP supports only
    http/sse MCP (grok — ``mcpCapabilities: {http, sse}``, no stdio). Context manager: spawns
    ``mcp_kvasir.py --http <port>`` on a free port, yields the HTTP :class:`MCPServer` entry,
    reaps on exit. We host the server; the agent connects — the membrane stays ours."""

    def __init__(self) -> None:
        import socket
        with socket.socket() as s:
            s.bind(("127.0.0.1", 0))
            self.port = s.getsockname()[1]
        self._proc = None

    def __enter__(self) -> MCPServer:
        import subprocess
        import time
        import urllib.request
        py = _VENV_PY if Path(_VENV_PY).exists() else "python"
        self._proc = subprocess.Popen(
            [py, str(REPO / "scripts/mcp_kvasir.py"), "--http", str(self.port)],
            cwd=str(REPO), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        url = f"http://127.0.0.1:{self.port}/mcp"
        for _ in range(60):  # wait for the uvicorn listener (imports take ~1-2s)
            try:
                urllib.request.urlopen(url, timeout=1)
                break
            except Exception as e:  # noqa: BLE001 — an HTTP status means it's UP
                if hasattr(e, "code"):
                    break
                time.sleep(0.25)
        return MCPServer(name="kvasir", url=url)

    def __exit__(self, *exc) -> None:
        if self._proc:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=5)
            except Exception:  # noqa: BLE001
                self._proc.kill()


# ── register loadouts: which tools each register-harness gets ────────────────────
# The semantic harness reasons against the kvasir MCP tools — PROVEN end-to-end (agent calls
# kvasir_check_consistency over MCP, gets the real verdict, states it in prose). Default ON;
# AEGIR_HARNESS_TOOLS=0 opts out (e.g. to isolate generation-latency measurements).
TOOLED_REGISTERS = set() if os.environ.get("AEGIR_HARNESS_TOOLS") == "0" else {"semantic"}


def kvasir_facts(ontology_omn: str) -> str:
    """Run the kvasir tools DETERMINISTICALLY (the pipeline owns them; the agent can't fake) and
    return a verified-schema-facts block to GROUND the semantic register up front. Complements the
    live MCP tools (also working): facts push the baseline truth into the prompt; the tools let
    the agent re-verify specific claims mid-generation."""
    try:
        from scripts.mcp_kvasir import check_consistency, ddl_profile
        import json as _json
        # FastMCP @tool leaves the plain function callable directly (no .fn accessor)
        prof = _json.loads(ddl_profile(ontology_omn))
        cons = _json.loads(check_consistency(ontology_omn))
        if "error" in prof:
            return ""
        return (f"- generated schema: {prof['n_elected']} entity tables, {prof['total_fks']} "
                f"foreign keys, {prof['n_junctions']} many-to-many junction tables, "
                f"{prof['n_lookups']} lookup tables; median table width {prof['width_median']} "
                f"columns\n- logical consistency (kvasir): {cons['verdict']}"
                + (f" — unsatisfiable: {cons['unsat_classes']}" if cons.get('unsat_classes') else ""))
    except Exception:  # noqa: BLE001
        return ""


def _augment_prompt(prompt: str, register: str, construct: dict, tooled: bool) -> str:
    if register == "semantic":
        facts = construct.get("kvasir_facts")
        if facts:
            prompt += ("\n\nVERIFIED SCHEMA FACTS — the kvasir DDL toolchain generated and checked "
                       "this schema from the ontology; ground your structural claims in these "
                       "(they are checked truth, not assumptions):\n" + facts)
        if tooled:
            prompt += ("\n\nMCP tools are also available (`ddl_profile`, `shacl_shapes`, "
                       "`check_consistency`) to re-verify any structural claim against the real DDL.")
    return prompt


# ── chapter assembly: prose AROUND fixed payload (tables + views embedded verbatim) ─────
_REGISTER_VOICE = {
    "natural": (
        "a professional technical reference chapter for practitioners of the domain. Teach the "
        "DOMAIN itself — its entities, processes, measurements, and operational relationships — "
        "the way a well-edited handbook chapter reads. NEVER use the words ontology, axiom, OWL, "
        "schema design, or class; the data tables are simply the domain's records."),
    "semantic": (
        "an ontology-grounded technical reference chapter explaining how this domain is MODELLED "
        "and how the model materializes as a relational schema. Teach the CONCEPTS: which entity "
        "types exist, how their attributes and cardinality-bounded relationships become columns, "
        "foreign keys, junction tables — and how each view's join reconstructs a domain fact from "
        "the normalized tables. Quote table/column/view names in backticks."),
}


def chapter_prompt(construct: dict, register: str) -> str:
    """The chapter-scale prompt: sectioned textbook prose written AROUND placement markers;
    the payload blocks are injected verbatim afterwards (`embed_payload`)."""
    blocks = construct.get("payload_markers") or []
    inventory = "\n".join(f"- {{{{{m}}}}}" for m in blocks)
    tables = ", ".join(t["name"] for t in construct.get("tables", []))
    views = ", ".join(v["name"] for v in construct.get("views", []))
    return (
        f"Write {_REGISTER_VOICE[register]}\n\n"
        "STRUCTURE — a full textbook chapter (aim for 1500-2500 words of prose):\n"
        "1. An untitled opening that frames the domain scenario.\n"
        "2. `##` sections teaching the material; weave the record identifiers and values from "
        "the data into the prose naturally.\n"
        "3. EMBED every payload block by writing its marker ALONE on its own line where the "
        "block belongs — e.g. {{TABLE:t_pump}} — then continue the prose AFTER it, referring "
        "to specific rows/values. Do NOT re-type or reformat any table yourself; the marker is "
        "replaced verbatim with the real table.\n"
        "4. Every view gets a section that INTERPRETS its joined result — what question the "
        "join answers, reading 2-3 concrete rows as evidence.\n"
        "5. A short closing synthesis.\n\n"
        f"PAYLOAD BLOCKS (every one MUST appear exactly once):\n{inventory}\n\n"
        f"Base tables: {tables}\nViews: {views}\n\n"
        "DATA (for reference when writing about values — the markers inject the real thing):\n"
        + construct.get("payload_preview", "") +
        "\n\nAll organizations, people, and products in the data are fictional; keep them so. "
        "Output ONLY the chapter markdown."
    )


def embed_payload(prose: str, blocks: "dict[str, str]") -> "tuple[str, dict]":
    """Substitute each ``{{MARKER}}`` with its fixed block (verbatim). Markers the agent
    dropped are appended under a Data Appendix — every block ships in every chapter,
    deterministically. Returns (chapter_md, stats)."""
    import re as _re
    placed, missing = 0, []
    for marker, block in blocks.items():
        pat = _re.compile(r"^[ \t]*\{\{" + _re.escape(marker) + r"\}\}[ \t]*$", _re.M)
        if pat.search(prose):
            prose = pat.sub(lambda _m, b=block: b, prose, count=1)
            prose = pat.sub("", prose)  # duplicates collapse
            placed += 1
        else:
            missing.append(marker)
    if missing:
        prose += "\n\n## Data appendix\n"
        for m in missing:
            prose += "\n" + blocks[m] + "\n"
    prose = _re.sub(r"\{\{[A-Z]+:[^}]+\}\}", "", prose)  # stray malformed markers
    return prose, {"placed": placed, "appendix": len(missing)}


@dataclass
class WorkItem:
    """One unit of the generation work queue."""
    construct: dict
    register: str            # natural | semantic
    backend: str             # local | grok | xai
    construct_id: str = ""
    tools: bool = True       # honor the register loadout (TOOLED_REGISTERS)


@dataclass
class ProseResult:
    construct_id: str
    register: str
    backend: str
    provider: str = ""
    prose: str = ""
    exchange: dict = field(default_factory=dict)
    error: str = ""


async def run_item(item: WorkItem, *, timeout: float = 600.0) -> ProseResult:
    """Run ONE register-specialized, tool-equipped ACP harness for a construct. Tool transport
    is backend-aware: stdio for agents that spawn servers (vibe-acp/local), streamable-http for
    agents whose ACP is http/sse-only (grok) — we host, the agent connects."""
    import contextlib
    home = tempfile.mkdtemp(prefix=f"harness_{item.register}_")
    try:
        spec, cfg_toml, model_id, provider = backend_spec(item.backend, home)
        if cfg_toml:
            Path(home, "config.toml").write_text(cfg_toml)
        tooled = item.tools and item.register in TOOLED_REGISTERS
        needs_http = item.backend.lower() in ("grok", "grok-build")
        payload = item.construct.get("payload_blocks") or {}
        with (kvasir_http_server() if tooled and needs_http else contextlib.nullcontext()) as http_srv:
            mcp = ([http_srv] if http_srv else [kvasir_mcp_server()]) if tooled else []
            base = (chapter_prompt(item.construct, item.register) if payload
                    else _prompt(item.construct, "prose", item.register, {}))
            prompt = _augment_prompt(base, item.register, item.construct, tooled)
            async with BaseACPClient(spec, fs_root=home, mcp_servers=mcp) as c:
                r = await c.prompt(prompt, timeout=timeout)
        prose = _strip_reasoning(r.text)
        embed_stats: dict = {}
        if payload and prose:
            prose, embed_stats = embed_payload(prose, payload)
        return ProseResult(
            construct_id=item.construct_id, register=item.register, backend=item.backend,
            provider=provider, prose=prose,
            exchange={"prompt": prompt, "response": r.text, "reasoning": r.thoughts,
                      "model": model_id, "tool_calls": r.tool_calls, "embed": embed_stats})
    except Exception as e:  # noqa: BLE001 — one failed cell must not sink the queue
        return ProseResult(item.construct_id, item.register, item.backend, error=str(e))


async def run_queue(items: list[WorkItem], pools: dict[str, int], *,
                    timeout: float = 900.0) -> list[ProseResult]:
    """Push the work queue through fixed per-backend pools (``asyncio.Semaphore`` per backend).
    ``pools`` = ``{backend: max_concurrent}`` (default 1 for any unnamed backend). ``timeout``
    is per item — full chapters with embedded payload run long under pool contention."""
    sems = {b: asyncio.Semaphore(n) for b, n in pools.items()}

    async def _guarded(it: WorkItem) -> ProseResult:
        sem = sems.setdefault(it.backend, asyncio.Semaphore(pools.get(it.backend, 1)))
        async with sem:
            return await run_item(it, timeout=timeout)

    return await asyncio.gather(*(_guarded(it) for it in items))


# ── logic table: the (register × backend) combinations to generate ──────────────
def logic_table(registers: list[str], backends: list[str]) -> list[tuple[str, str]]:
    """The cartesian combinations the work queue realizes (natural/semantic × local/grok/…)."""
    return [(reg, be) for reg in registers for be in backends]


def build_queue(constructs: dict[str, dict], combos: list[tuple[str, str]]) -> list[WorkItem]:
    """``{construct_id: construct}`` × ``[(register, backend)]`` → the flat work-item list."""
    return [WorkItem(construct=c, register=reg, backend=be, construct_id=cid)
            for cid, c in constructs.items() for reg, be in combos]


def generate(constructs: dict[str, dict], combos: list[tuple[str, str]],
             pools: dict[str, int]) -> list[ProseResult]:
    """Sync entry point: realize the (construct × register × backend) matrix through the pools."""
    return asyncio.run(run_queue(build_queue(constructs, combos), pools))
