"""Parallel register-specialized ACP prose harnesses + work-queue driver (#141).

RH architecture (2026-07-04): prose is generated by a WORK QUEUE of ``(construct × register ×
backend)`` items pushed through FIXED-SIZE per-backend worker pools. Each item runs one ACP agent
harness — register-specialized (natural / semantic) and tool/resource-equipped over MCP (the
semantic harness gets kvasir DDL-check tools + a SHACL grounding resource; more tools per the
loadout roadmap). The agent iterates against its tools while writing; the CLIENT owns the tools so
the agent can check but never fake (the membrane doctrine, ``refine/acp/client.py``).

Backends are pluggable — ``local`` (mistral vibe-acp → Qwen3.6 on the engine's :8100 vLLM),
``grok`` (Grok Build subscription), ``xai`` (metered API). Both registers run on ``local`` first;
grok swaps in as the local+API worker mix shifts (a fixed pool per backend caps concurrency).

The unit is :func:`run_item`; the driver is :func:`run_queue` (per-backend ``asyncio.Semaphore``),
which generalizes to a Metaflow ``foreach`` with resource limits.
"""
from __future__ import annotations

import asyncio
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from aegir.refine._propose import _prompt, _strip_reasoning
from aegir.refine.acp import BaseACPClient, MCPServer, grok_acp_spec, vibe_acp_spec

REPO = Path(__file__).resolve().parents[3]
FORK = os.environ.get("AEGIR_FORK_DIR", str(REPO / "components/oss-mistral-cli"))

# vibe-acp config pointing at the local vLLM OpenAI endpoint (the engine's :8100).
_LOCAL_TOML = (
    'active_model = "local"\nsystem_prompt_id = "aegir_writer"\n'
    '[[providers]]\nname = "local-vllm"\napi_base = "http://127.0.0.1:8100/v1"\n'
    'api_style = "openai"\n[[models]]\nname = "instruct"\nprovider = "local-vllm"\nalias = "local"\n'
)


def backend_spec(backend: str, home: str):
    """``(AgentSpec, cfg_toml|None, model_id, provider)`` for a NAMED backend (the work-queue
    parameter form of ``_propose._agent_spec``'s env form). ``local`` → vibe-acp→Qwen3.6;
    ``grok`` → the unmetered Grok Build CLI; ``xai`` → the metered xAI API."""
    b = backend.lower()
    if b in ("grok", "grok-build"):
        return grok_acp_spec(home), None, os.environ.get("AEGIR_GROK_MODEL", "grok"), "grok-build"
    if b in ("xai", "xai-api"):
        if not os.environ.get("XAI_API_KEY"):
            raise RuntimeError("backend=xai but XAI_API_KEY is unset (metered)")
        model = os.environ.get("AEGIR_XAI_MODEL", "grok-4.3")
        toml = ('active_model = "remote"\nsystem_prompt_id = "aegir_writer"\n'
                '[[providers]]\nname = "xai"\napi_base = "https://api.x.ai/v1"\n'
                'api_style = "openai"\napi_key_env_var = "XAI_API_KEY"\n'
                f'[[models]]\nname = "{model}"\nprovider = "xai"\nalias = "remote"\n')
        return vibe_acp_spec(FORK, home), toml, model, "xai-api"
    return vibe_acp_spec(FORK, home), _LOCAL_TOML, "instruct", "engine"


def kvasir_mcp_server() -> MCPServer:
    """The kvasir DDL/consistency/SHACL toolbox as a stdio MCP server (``scripts/mcp_kvasir.py``)."""
    return MCPServer(name="kvasir", command="uv",
                     args=["run", "--no-sync", "python", "scripts/mcp_kvasir.py"], cwd=str(REPO))


# ── register loadouts: which tools each register-harness gets ────────────────────
# The semantic harness reasons against the kvasir MCP tools. The MCP SERVER works (clean
# initialize), but the vibe-acp+Qwen tool-CALLING path currently returns empty when servers are
# attached — a separate integration fix. Gated behind AEGIR_HARNESS_TOOLS=1 until debugged; the
# two-register architecture stands without it (the tools are an enhancement, not the register).
TOOLED_REGISTERS = {"semantic"} if os.environ.get("AEGIR_HARNESS_TOOLS") == "1" else set()


def _augment_prompt(prompt: str, register: str, tooled: bool) -> str:
    if tooled and register == "semantic":
        return (prompt + "\n\nYou have MCP tools available: `ddl_profile`, `shacl_shapes`, and "
                "`check_consistency` over an OWL Manchester ontology. When you make a structural "
                "claim about the schema (a foreign key, a cardinality, a constraint), you MAY call "
                "a tool to verify it against the real generated DDL before asserting it.")
    return prompt


@dataclass
class WorkItem:
    """One unit of the generation work queue."""
    construct: dict
    register: str            # natural | semantic
    backend: str             # local | grok | xai
    construct_id: str = ""
    tools: bool = True       # honor the register loadout (TOOLED_REGISTERS)


@dataclass
class ProseResult:
    construct_id: str
    register: str
    backend: str
    provider: str = ""
    prose: str = ""
    exchange: dict = field(default_factory=dict)
    error: str = ""


async def run_item(item: WorkItem, *, timeout: float = 600.0) -> ProseResult:
    """Run ONE register-specialized, tool-equipped ACP harness for a construct."""
    home = tempfile.mkdtemp(prefix=f"harness_{item.register}_")
    try:
        spec, cfg_toml, model_id, provider = backend_spec(item.backend, home)
        if cfg_toml:
            Path(home, "config.toml").write_text(cfg_toml)
        tooled = item.tools and item.register in TOOLED_REGISTERS
        mcp = [kvasir_mcp_server()] if tooled else []
        prompt = _augment_prompt(_prompt(item.construct, "prose", item.register, {}),
                                 item.register, tooled)
        async with BaseACPClient(spec, fs_root=home, mcp_servers=mcp) as c:
            r = await c.prompt(prompt, timeout=timeout)
        return ProseResult(
            construct_id=item.construct_id, register=item.register, backend=item.backend,
            provider=provider, prose=_strip_reasoning(r.text),
            exchange={"prompt": prompt, "response": r.text, "reasoning": r.thoughts,
                      "model": model_id, "tool_calls": r.tool_calls})
    except Exception as e:  # noqa: BLE001 — one failed cell must not sink the queue
        return ProseResult(item.construct_id, item.register, item.backend, error=str(e))


async def run_queue(items: list[WorkItem], pools: dict[str, int]) -> list[ProseResult]:
    """Push the work queue through fixed per-backend pools (``asyncio.Semaphore`` per backend).
    ``pools`` = ``{backend: max_concurrent}`` (default 1 for any unnamed backend)."""
    sems = {b: asyncio.Semaphore(n) for b, n in pools.items()}

    async def _guarded(it: WorkItem) -> ProseResult:
        sem = sems.setdefault(it.backend, asyncio.Semaphore(pools.get(it.backend, 1)))
        async with sem:
            return await run_item(it)

    return await asyncio.gather(*(_guarded(it) for it in items))


# ── logic table: the (register × backend) combinations to generate ──────────────
def logic_table(registers: list[str], backends: list[str]) -> list[tuple[str, str]]:
    """The cartesian combinations the work queue realizes (natural/semantic × local/grok/…)."""
    return [(reg, be) for reg in registers for be in backends]


def build_queue(constructs: dict[str, dict], combos: list[tuple[str, str]]) -> list[WorkItem]:
    """``{construct_id: construct}`` × ``[(register, backend)]`` → the flat work-item list."""
    return [WorkItem(construct=c, register=reg, backend=be, construct_id=cid)
            for cid, c in constructs.items() for reg, be in combos]


def generate(constructs: dict[str, dict], combos: list[tuple[str, str]],
             pools: dict[str, int]) -> list[ProseResult]:
    """Sync entry point: realize the (construct × register × backend) matrix through the pools."""
    return asyncio.run(run_queue(build_queue(constructs, combos), pools))
